version: '3'

services:
  kbos:
    build: ../../data_engine/
    image: kbos_listeners
    entrypoint: python /code/engine_main.py
    volumes:
      - ../../data:/data:Z
    env_file:
      - ./envs/directories.env
      - ./envs/engine.env
    environment: 
      - FLAG_COND=kbos
  klax:
    build: ../../data_engine/
    image: klax_listeners
    entrypoint: python /code/engine_main.py
    volumes:
      - ../../data:/data:Z
    env_file:
      - ./envs/directories.env
      - ./envs/engine.env
    environment: 
      - FLAG_COND=klax
  db_updator:
    build: ../../data_engine/
    image: db_updator
    entrypoint: python /code/database_updator.py
    volumes:
      - ../../data:/data:Z
    env_file:
      - ./envs/directories.env
    environment: 
      - RERUN=120
    restart: always
  audio_converter:
    build: ../../data_engine/
    image: audio_converter
    entrypoint: python /code/audio_converter.py
    volumes:
      - ../../data:/data:Z
    env_file: 
      - ./envs/directories.env
    environment: 
      - RERUN=30
    restart: always