Description: Project Resources
Parameters:
  ResourcePrefix:
    Description: Name Prefix for all the resources
    Type: String
    Default: project-uranus
Resources:
  ProjectBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: !Sub '${ResourcePrefix}-main-bucket'
  ProjectDataPullingECR:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub '${ResourcePrefix}-data-engine'